/******************************************************************************/
/*                 Generated by IBExpert 21/10/2023 09:20:12                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;

/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/

CREATE TABLE SITUACAONEGOCIACAO (
    IDSITUACAONEGOCIACAO  INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DESCRICAO             VARCHAR(20) NOT NULL
);

ALTER TABLE SITUACAONEGOCIACAO ALTER IDSITUACAONEGOCIACAO RESTART WITH 4;
ALTER TABLE SITUACAONEGOCIACAO ADD CONSTRAINT PK_SITUACAONEGOCIACAO PRIMARY KEY (IDSITUACAONEGOCIACAO);

INSERT INTO SITUACAONEGOCIACAO (IDSITUACAONEGOCIACAO, DESCRICAO) VALUES (1, 'PENDENTE');
INSERT INTO SITUACAONEGOCIACAO (IDSITUACAONEGOCIACAO, DESCRICAO) VALUES (2, 'APROVADA');
INSERT INTO SITUACAONEGOCIACAO (IDSITUACAONEGOCIACAO, DESCRICAO) VALUES (3, 'CONCLUIR');
INSERT INTO SITUACAONEGOCIACAO (IDSITUACAONEGOCIACAO, DESCRICAO) VALUES (4, 'CANCELADA');

/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/
CREATE TABLE PESSOA (
    IDPESSOA      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NOME          VARCHAR(100) NOT NULL,
    CPFCNPJ       VARCHAR(14) NOT NULL,
    TIPOENTIDADE  INTEGER
);

ALTER TABLE PESSOA ALTER IDPESSOA RESTART WITH 0;
ALTER TABLE PESSOA ADD CONSTRAINT UNQ1_PESSOA UNIQUE (CPFCNPJ);
ALTER TABLE PESSOA ADD CONSTRAINT PK_PESSOA PRIMARY KEY (IDPESSOA);


/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/

CREATE TABLE PESSOALIMITECREDITO (
    IDPESSOAPRODUTOR      INTEGER NOT NULL,
    IDPESSOADISTRIBUIDOR  INTEGER NOT NULL,
    LIMITECREDITO         NUMERIC(15,2) NOT NULL
);

ALTER TABLE PESSOALIMITECREDITO ADD CONSTRAINT FK_PESSOALIMITECREDITO_1 FOREIGN KEY (IDPESSOAPRODUTOR) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE PESSOALIMITECREDITO ADD CONSTRAINT FK_PESSOALIMITECREDITO_2 FOREIGN KEY (IDPESSOADISTRIBUIDOR) REFERENCES PESSOA (IDPESSOA);

/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/

CREATE TABLE PRODUTO (
    IDPRODUTO   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    DESCRICAO   VARCHAR(100) NOT NULL,
    PRECOVENDA  NUMERIC(15,2) NOT NULL
);

ALTER TABLE PRODUTO ALTER IDPRODUTO RESTART WITH 0;
ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (IDPRODUTO);


/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/

CREATE TABLE NEGOCIACAO (
    IDNEGOCIACAO    INTEGER GENERATED BY DEFAULT AS IDENTITY,
    IDPRODUTOR      INTEGER NOT NULL,
    IDDISTRIBUIDOR  INTEGER NOT NULL,
    IDSITUACAO      INTEGER NOT NULL
);

ALTER TABLE NEGOCIACAO ALTER IDNEGOCIACAO RESTART WITH 0;
ALTER TABLE NEGOCIACAO ADD CONSTRAINT PK_NEGOCIACAO PRIMARY KEY (IDNEGOCIACAO);
ALTER TABLE NEGOCIACAO ADD CONSTRAINT FK_NEGOCIACAO_1 FOREIGN KEY (IDPRODUTOR) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE NEGOCIACAO ADD CONSTRAINT FK_NEGOCIACAO_2 FOREIGN KEY (IDDISTRIBUIDOR) REFERENCES PESSOA (IDPESSOA);
ALTER TABLE NEGOCIACAO ADD CONSTRAINT FK_NEGOCIACAO_3 FOREIGN KEY (IDSITUACAO) REFERENCES SITUACAONEGOCIACAO (IDSITUACAONEGOCIACAO);


/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/

CREATE TABLE NEGOCIACAOPRODUTOS (
    IDITEM        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    IDNEGOCIACAO  INTEGER NOT NULL,
    IDPRODUTO     INTEGER NOT NULL,
    PRECO         NUMERIC(15,2),
    QUANTIDADE    NUMERIC(15,2)
);

ALTER TABLE NEGOCIACAOPRODUTOS ALTER IDITEM RESTART WITH 0;
ALTER TABLE NEGOCIACAOPRODUTOS ADD CONSTRAINT PK_NEGOCIACAOPRODUTOS PRIMARY KEY (IDITEM);
ALTER TABLE NEGOCIACAOPRODUTOS ADD CONSTRAINT FK_NEGOCIACAOPRODUTOS_1 FOREIGN KEY (IDNEGOCIACAO) REFERENCES NEGOCIACAO (IDNEGOCIACAO);
ALTER TABLE NEGOCIACAOPRODUTOS ADD CONSTRAINT FK_NEGOCIACAOPRODUTOS_2 FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO);
